---
- name: Check /etc/pam.d/sshd
  ansible.builtin.stat:
    path: /etc/pam.d/sshd
  register: etc_pam_sshd

- name: Copy to correct location
  when: not etc_pam_sshd.stat.exists
  block:
    - name: Check /usr/etc/pam.d/sshd
      ansible.builtin.stat:
        path: /usr/etc/pam.d/sshd
      register: locate_pam_sshd

    - name: Check /usr/lib/pam.d/sshd
      ansible.builtin.stat:
        path: /usr/lib/pam.d/sshd
      register: locate_pam_sshd
      when:
        - locate_pam_sshd.stat.exists is defined
        - not locate_pam_sshd.stat.exists

    - name: Copy located pam.d/sshd to /etc/pam.d/sshd
      ansible.builtin.copy:
        src: "{{ locate_pam_sshd.stat.path }}"
        dest: /etc/pam.d/sshd
        owner: root
        group: root
        mode: "0644"
        remote_src: true
      when:
        - locate_pam_sshd.stat.exists is defined
        - locate_pam_sshd.stat.exists is true
